-- 工业物联网设备管理与实时监控平台 数据库初始化
CREATE DATABASE IF NOT EXISTS iot_platform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE iot_platform;

-- 用户表
CREATE TABLE sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT 'BCrypt密码',
    nickname VARCHAR(50) COMMENT '昵称',
    email VARCHAR(100) COMMENT '邮箱',
    role VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '角色 ADMIN/USER',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0禁用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 产品表
CREATE TABLE product (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    product_key VARCHAR(32) NOT NULL UNIQUE COMMENT '产品唯一标识',
    name VARCHAR(100) NOT NULL COMMENT '产品名称',
    protocol VARCHAR(20) DEFAULT 'MQTT' COMMENT '接入协议 MQTT/TCP',
    description VARCHAR(500) COMMENT '产品描述',
    status TINYINT DEFAULT 1 COMMENT '状态',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品表';

-- 设备表
CREATE TABLE device (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    device_name VARCHAR(64) NOT NULL UNIQUE COMMENT '设备唯一标识',
    product_key VARCHAR(32) NOT NULL COMMENT '所属产品Key',
    device_secret VARCHAR(64) NOT NULL COMMENT '设备密钥',
    status VARCHAR(20) DEFAULT 'INACTIVE' COMMENT '状态 ONLINE/OFFLINE/INACTIVE',
    last_ip VARCHAR(50) COMMENT '最后在线IP',
    last_online_time DATETIME COMMENT '最后在线时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    INDEX idx_product_key (product_key),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备表';

-- 告警规则表
CREATE TABLE alarm_rule (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rule_name VARCHAR(100) NOT NULL COMMENT '规则名称',
    product_key VARCHAR(32) NOT NULL COMMENT '产品Key',
    metric VARCHAR(50) NOT NULL COMMENT '监控指标',
    operator VARCHAR(10) NOT NULL COMMENT '比较运算符 > < =',
    threshold DOUBLE NOT NULL COMMENT '阈值',
    level VARCHAR(20) DEFAULT 'WARN' COMMENT '级别 INFO/WARN/CRITICAL',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警规则表';

-- 初始管理员账号 (密码: admin123, BCrypt)
INSERT INTO sys_user (username, password, nickname, role, status) VALUES
('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', '管理员', 'ADMIN', 1);
